title: Russian Cultural Exchange
email: russianculturalexchange@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rcemtl.github.io"
twitter_username: jekyllrb
github_username:  jekyll
permalink: :title

markdown: kramdown

defaults:
    - {scope: {path: ""}, values: {layout: "post"}}


prose:
  rooturl: '_posts'
  siteurl: 'http://rcemtl.github.io'
  media: 'img'